# Generated by Django 4.1.3 on 2022-11-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ageNow', models.IntegerField(blank=True, null=True)),
                ('alldressing', models.TextField(blank=True, null=True)),
                ('occrAdd', models.TextField(blank=True, null=True)),
                ('occrDate', models.DateField(blank=True, null=True)),
                ('writngTarget', models.TextField(blank=True)),
            ],
        ),
    ]
