# Generated by Django 4.1.3 on 2022-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchild',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
