# Generated by Django 4.1.3 on 2022-11-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mchild_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mchild',
            name='gender',
            field=models.TextField(blank=True, null=True),
        ),
    ]
