# Generated by Django 4.1.3 on 2022-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_mchild_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='mchild',
            name='inform',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mchild',
            name='writngTarget',
            field=models.TextField(blank=True, null=True),
        ),
    ]
